/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author arnav
 */
public class AddEmployeeFrame extends javax.swing.JFrame {
    private MyHashTable theHT;
    
    /**
     * Creates new form addEmployeeFrame
     */
    public AddEmployeeFrame() {
        initComponents();
        msgLabel.setText(" ");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeType = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        selectFTEButton = new javax.swing.JRadioButton();
        selectPTEButton = new javax.swing.JRadioButton();
        employeeNumberField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        salaryField = new javax.swing.JTextField();
        deductRateField = new javax.swing.JTextField();
        hoursPerWeekField = new javax.swing.JTextField();
        weeksPerYearField = new javax.swing.JTextField();
        workLocField = new javax.swing.JTextField();
        addToTableButton = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Add New Employee");

        employeeType.add(selectFTEButton);
        selectFTEButton.setText("Full Time");
        selectFTEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFTEButtonActionPerformed(evt);
            }
        });

        employeeType.add(selectPTEButton);
        selectPTEButton.setText("Part Time");
        selectPTEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPTEButtonActionPerformed(evt);
            }
        });

        employeeNumberField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        employeeNumberField.setText("Employee Number");

        genderField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        genderField.setText("Gender");

        firstNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstNameField.setText("First Name");

        lastNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastNameField.setText("Last Name");

        salaryField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        salaryField.setText("Pay (#)");

        deductRateField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deductRateField.setText("Deduct Rate (0.##)");

        hoursPerWeekField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hoursPerWeekField.setText("Hours Per Week (#)");

        weeksPerYearField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        weeksPerYearField.setText("Weeks Per Year (#)");

        workLocField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        workLocField.setText("Work Location");

        addToTableButton.setBackground(new java.awt.Color(0, 204, 51));
        addToTableButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addToTableButton.setForeground(new java.awt.Color(255, 255, 255));
        addToTableButton.setText("ADD");
        addToTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddButtonClick(evt);
            }
        });

        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgLabel.setText("<Msg>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addToTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(workLocField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(selectFTEButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectPTEButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(salaryField)
                                .addComponent(deductRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hoursPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeNumberField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(weeksPerYearField))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectFTEButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectPTEButton)
                    .addComponent(employeeNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deductRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workLocField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(addToTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectFTEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFTEButtonActionPerformed
        hoursPerWeekField.setVisible(false);
        weeksPerYearField.setVisible(false);
        salaryField.setText("Annual Pay (#)");
        
    }//GEN-LAST:event_selectFTEButtonActionPerformed

    private void selectPTEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPTEButtonActionPerformed
        hoursPerWeekField.setVisible(true);
        weeksPerYearField.setVisible(true); 
        salaryField.setText("Hourly Pay (#)");
    }//GEN-LAST:event_selectPTEButtonActionPerformed

    private void onAddButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddButtonClick
        try {
            int newEmpNumber = Integer.parseInt(employeeNumberField.getText());
            String newEmpFirstName = firstNameField.getText();
            String newEmpLastName = lastNameField.getText();
            String newEmpWorkLoc = workLocField.getText();
            double newEmpDeductRate = Double.parseDouble(deductRateField.getText());
            String newEmpGender = genderField.getText();
            
            if (theHT.getFromTable(newEmpNumber) != null){
                msgLabel.setText("An employee with this number already exists");
            } else if (selectFTEButton.isSelected()){
                double newEmpSalary = Double.parseDouble(salaryField.getText());
                FTE theNewEmp = new FTE(newEmpNumber,newEmpFirstName, 
                        newEmpLastName, newEmpWorkLoc, newEmpDeductRate, newEmpSalary, newEmpGender);
                theHT.addToTable(theNewEmp);
                msgLabel.setText("Added " + theNewEmp.getFirstName());
                
            } else if (selectPTEButton.isSelected()){
                    
                double newEmpWage = Double.parseDouble(salaryField.getText());
                int newEmpHoursPerWeek = Integer.parseInt(hoursPerWeekField.getText());
                int newEmpWeeksPerYear = Integer.parseInt(weeksPerYearField.getText());
            
                PTE theNewEmp = new PTE(newEmpNumber,newEmpFirstName, 
                        newEmpLastName, newEmpWorkLoc, newEmpDeductRate,newEmpWage, 
                        newEmpHoursPerWeek, newEmpWeeksPerYear, newEmpGender);
                theHT.addToTable(theNewEmp);
                msgLabel.setText("Added " + theNewEmp.getFirstName());
            } else {
                msgLabel.setText("Select an employee type");
            }
            
            
        } catch (Exception e){
            msgLabel.setText("Error: Incorrect input");
        }
        weeksPerYearField.setVisible(true);
        hoursPerWeekField.setVisible(true);
        employeeType.clearSelection();
        salaryField.setText("Pay (#)");
        
    }//GEN-LAST:event_onAddButtonClick

    public void setHashTable(MyHashTable theRefValue){
        theHT = theRefValue;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeeFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToTableButton;
    private javax.swing.JTextField deductRateField;
    private javax.swing.JTextField employeeNumberField;
    private javax.swing.ButtonGroup employeeType;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField genderField;
    private javax.swing.JTextField hoursPerWeekField;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JTextField salaryField;
    private javax.swing.JRadioButton selectFTEButton;
    private javax.swing.JRadioButton selectPTEButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField weeksPerYearField;
    private javax.swing.JTextField workLocField;
    // End of variables declaration//GEN-END:variables
}
