/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author arnav
 */
public class EditEmployeeFrame extends javax.swing.JFrame {
    public MyHashTable theHT;
    /**
     * Creates new form editEmployeeFrame
     */
    public EditEmployeeFrame() {
        initComponents();
        
        msgLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        inputNumberLabel = new javax.swing.JLabel();
        employeeNumberFindField = new javax.swing.JTextField();
        findEmpButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeAttributes = new javax.swing.JTable();
        msgLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        saveEmpButton = new javax.swing.JButton();
        saveNumLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Edit Employee");

        inputNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputNumberLabel.setText("Enter Employee Number:");

        employeeNumberFindField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        employeeNumberFindField.setText("------");

        findEmpButton.setText("Find Employee");
        findEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findEmpButtonActionPerformed(evt);
            }
        });

        employeeAttributes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Type", "Emp. Num.", "First Name", "Last Name", "Gender", "Work Location", "Pay", "Hours per Week", "Weeks per Year", "Deduct Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeeAttributes);

        msgLabel.setText("<Msg>");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit values in the table, and click save, to edit an employee.");

        saveEmpButton.setText("SAVE");
        saveEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEmpButtonActionPerformed(evt);
            }
        });

        saveNumLabel.setText("######");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inputNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(employeeNumberFindField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(findEmpButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveNumLabel)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(msgLabel)
                        .addGap(360, 360, 360))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNumberLabel)
                    .addComponent(employeeNumberFindField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findEmpButton)
                    .addComponent(saveNumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(saveEmpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgLabel)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findEmpButtonActionPerformed
        int targetEmployeeNum = Integer.parseInt(employeeNumberFindField.getText());
        EmployeeInfo targetEmp;
        if (theHT.getFromTable(targetEmployeeNum) != null){
            targetEmp = theHT.getFromTable(targetEmployeeNum);
        } else {
            msgLabel.setText("Employee Not Found");
            return;
        }
        saveNumLabel.setText("" + targetEmployeeNum);
        if (theHT.getFromTable(targetEmployeeNum) == null){
            msgLabel.setText("Employee not found");
            return;
        }
        if (targetEmp instanceof FTE){
            FTE targetFTE = (FTE) theHT.getFromTable(targetEmployeeNum);
            employeeAttributes.getModel().setValueAt("FTE", 0, 0);
            employeeAttributes.getModel().setValueAt(targetFTE.getEmpNumber(), 0, 1);
            employeeAttributes.getModel().setValueAt(targetFTE.getFirstName(), 0, 2);
            employeeAttributes.getModel().setValueAt(targetFTE.getLastName(), 0, 3);
            employeeAttributes.getModel().setValueAt(targetFTE.getGender(), 0, 4);
            employeeAttributes.getModel().setValueAt(targetFTE.getWorkLoc(), 0, 5);
            employeeAttributes.getModel().setValueAt(targetFTE.getSalary(), 0, 6);
            employeeAttributes.getModel().setValueAt(-1, 0, 7);
            employeeAttributes.getModel().setValueAt(-1, 0, 8);
            employeeAttributes.getModel().setValueAt(targetFTE.getDeductRate(), 0, 9);    
        } else if (targetEmp instanceof PTE){

            PTE targetPTE = (PTE) theHT.getFromTable(targetEmployeeNum);
            employeeAttributes.getModel().setValueAt("PTE", 0, 0);
            employeeAttributes.getModel().setValueAt(targetPTE.getEmpNumber(), 0, 1);
            employeeAttributes.getModel().setValueAt(targetPTE.getFirstName(), 0, 2);
            employeeAttributes.getModel().setValueAt(targetPTE.getLastName(), 0, 3);
            employeeAttributes.getModel().setValueAt(targetPTE.getGender(), 0, 4);
            employeeAttributes.getModel().setValueAt(targetPTE.getWorkLoc(), 0, 5);
            employeeAttributes.getModel().setValueAt(targetPTE.getHourlyWage(), 0, 6);
            employeeAttributes.getModel().setValueAt(targetPTE.getHoursPerWeek(), 0, 7);
            employeeAttributes.getModel().setValueAt(targetPTE.getWeeksPerYear(), 0, 8);
            employeeAttributes.getModel().setValueAt(targetPTE.getDeductRate(), 0, 9);
        } else {
            msgLabel.setText("Error");
        }
    }//GEN-LAST:event_findEmpButtonActionPerformed

    private void saveEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEmpButtonActionPerformed
        
        
        try {
            int empNum = (int) employeeAttributes.getModel().getValueAt(0, 1);
            String fName = (String) employeeAttributes.getModel().getValueAt(0, 2);
            String lName = (String) employeeAttributes.getModel().getValueAt(0, 3);
            String gender = (String) employeeAttributes.getModel().getValueAt(0, 4);
            String workLoc = (String) employeeAttributes.getModel().getValueAt(0, 5);
            double deductRate = (double) employeeAttributes.getModel().getValueAt(0, 9);
        
            if ("FTE".equals(employeeAttributes.getModel().getValueAt(0,0))){ 
                theHT.removeFromTable(Integer.parseInt(saveNumLabel.getText()));
                double salary = (double) employeeAttributes.getModel().getValueAt(0, 6);
                FTE edittedEmp = new FTE(empNum, fName, lName, workLoc, deductRate, salary, gender);
                theHT.addToTable(edittedEmp);
                msgLabel.setText("Success");
            } else if ("PTE".equals(employeeAttributes.getModel().getValueAt(0,0))){
                theHT.removeFromTable(Integer.parseInt(saveNumLabel.getText()));
                double hourlyWage = (double) employeeAttributes.getModel().getValueAt(0, 6);
                double hoursPerWeek = (double) employeeAttributes.getModel().getValueAt(0, 7);
                double weeksPerYear = (double) employeeAttributes.getModel().getValueAt(0, 8);
                PTE edittedEmp = new PTE(empNum, fName, lName, workLoc, 
                    deductRate, hourlyWage, hoursPerWeek, weeksPerYear, gender);
                theHT.addToTable(edittedEmp);
                msgLabel.setText("Success");
            } else {
                msgLabel.setText("Invalid Employee Type");
            }
        } catch(Exception e){
            msgLabel.setText("Invalid Input Values");
        }
    }//GEN-LAST:event_saveEmpButtonActionPerformed
    public void setHashTable(MyHashTable theRefValue){
        theHT = theRefValue;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable employeeAttributes;
    private javax.swing.JTextField employeeNumberFindField;
    private javax.swing.JButton findEmpButton;
    private javax.swing.JLabel inputNumberLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JButton saveEmpButton;
    private javax.swing.JLabel saveNumLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
