/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author arnav
 */
public class MenuFrame extends javax.swing.JFrame {
    
    public MyHashTable theHT;
    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
        theHT = new MyHashTable(10);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        addEmpButton = new javax.swing.JButton();
        deleteEmpButton = new javax.swing.JButton();
        editEmpButton = new javax.swing.JButton();
        displayEmpsButton = new javax.swing.JButton();
        saveToFileButtons = new javax.swing.JButton();
        loadFromFileButton = new javax.swing.JButton();
        summaryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("All-In-One Employee Management System");

        addEmpButton.setBackground(new java.awt.Color(0, 204, 51));
        addEmpButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addEmpButton.setForeground(new java.awt.Color(255, 255, 255));
        addEmpButton.setText("Add Employee");
        addEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpButtonActionPerformed(evt);
            }
        });

        deleteEmpButton.setBackground(new java.awt.Color(204, 0, 0));
        deleteEmpButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteEmpButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteEmpButton.setText("Delete Employee");
        deleteEmpButton.setMaximumSize(new java.awt.Dimension(108, 22));
        deleteEmpButton.setMinimumSize(new java.awt.Dimension(108, 22));
        deleteEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmpButtonActionPerformed(evt);
            }
        });

        editEmpButton.setBackground(new java.awt.Color(255, 204, 0));
        editEmpButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editEmpButton.setForeground(new java.awt.Color(255, 255, 255));
        editEmpButton.setText("Edit Employee");
        editEmpButton.setMaximumSize(new java.awt.Dimension(108, 22));
        editEmpButton.setMinimumSize(new java.awt.Dimension(108, 22));
        editEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmpButtonActionPerformed(evt);
            }
        });

        displayEmpsButton.setBackground(new java.awt.Color(153, 153, 255));
        displayEmpsButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        displayEmpsButton.setForeground(new java.awt.Color(255, 255, 255));
        displayEmpsButton.setText("Display Emps.");
        displayEmpsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayEmpsButtonActionPerformed(evt);
            }
        });

        saveToFileButtons.setBackground(new java.awt.Color(0, 153, 204));
        saveToFileButtons.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveToFileButtons.setForeground(new java.awt.Color(255, 255, 255));
        saveToFileButtons.setText("Save To File");
        saveToFileButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToFileButtonsActionPerformed(evt);
            }
        });

        loadFromFileButton.setBackground(new java.awt.Color(255, 153, 0));
        loadFromFileButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loadFromFileButton.setForeground(new java.awt.Color(255, 255, 255));
        loadFromFileButton.setText("Load From File");
        loadFromFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFromFileButtonActionPerformed(evt);
            }
        });

        summaryButton.setBackground(new java.awt.Color(0, 0, 102));
        summaryButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        summaryButton.setForeground(new java.awt.Color(255, 255, 255));
        summaryButton.setText("Overview");
        summaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addEmpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editEmpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveToFileButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displayEmpsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loadFromFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(summaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayEmpsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveToFileButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadFromFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(summaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpButtonActionPerformed
        AddEmployeeFrame theAddEmployeeFrame = new AddEmployeeFrame();
        theAddEmployeeFrame.setVisible(true);
        theAddEmployeeFrame.setHashTable(theHT);
    }//GEN-LAST:event_addEmpButtonActionPerformed

    private void deleteEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmpButtonActionPerformed
        RemoveEmpFrame theRemoveFrame = new RemoveEmpFrame();
        theRemoveFrame.setVisible(true);
        theRemoveFrame.setHashTable(theHT);
    }//GEN-LAST:event_deleteEmpButtonActionPerformed

    private void editEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmpButtonActionPerformed
        EditEmployeeFrame theEditFrame = new EditEmployeeFrame();
        theEditFrame.setVisible(true);
        theEditFrame.setHashTable(theHT);
    }//GEN-LAST:event_editEmpButtonActionPerformed

    private void displayEmpsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayEmpsButtonActionPerformed
        DisplayEmployeesFrame theDisplayFrame = new DisplayEmployeesFrame();
        theDisplayFrame.setVisible(true);
        theDisplayFrame.setHashTable(theHT);
    }//GEN-LAST:event_displayEmpsButtonActionPerformed

    private void saveToFileButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToFileButtonsActionPerformed
        SaveToFileFrame theSaveFrame = new SaveToFileFrame();
        theSaveFrame.setVisible(true);
        theSaveFrame.setHashTable(theHT);
    }//GEN-LAST:event_saveToFileButtonsActionPerformed

    private void loadFromFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFromFileButtonActionPerformed
        LoadEmpsFrame theLoadFrame = new LoadEmpsFrame();
        theLoadFrame.setVisible(true);
        theLoadFrame.setHashTable(theHT);
    }//GEN-LAST:event_loadFromFileButtonActionPerformed

    private void summaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryButtonActionPerformed
        OverviewFrame theOverviewFrame = new OverviewFrame();
        theOverviewFrame.setVisible(true);
        theOverviewFrame.setHashTable(theHT);
    }//GEN-LAST:event_summaryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmpButton;
    private javax.swing.JButton deleteEmpButton;
    private javax.swing.JButton displayEmpsButton;
    private javax.swing.JButton editEmpButton;
    private javax.swing.JButton loadFromFileButton;
    private javax.swing.JButton saveToFileButtons;
    private javax.swing.JButton summaryButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
